Aws undeploy instance
CloudSlang/cloud-slang-content pull request #1405
Opened 2021-09-02 10:53 UTC by KalyankarRajesh

Created AWS undeploy instance with worked group

2021-09-02 11:09 UTC, umavanth21 requested changes
Do we need to mention proxy port default value

2021-09-02 11:35 UTC, KalyankarRajesh commented
> Do we need to mention proxy port default value

Updated the description and removed the default value.

2021-09-02 11:38 UTC, umavanth21 approved these changes
Approving

2021-09-03 05:53 UTC, patmante approved these changes

2021-09-03 05:54 UTC, merged