Microsoft Azure Active Directory Integration
CloudSlang/cloud-slang-content pull request #1421
Opened 2021-09-15 11:27 UTC by AlexandruPresecan

Added sl files for create_user, delete_user, is_user_enabled and get_authetication_token operations.

2021-09-15 11:32 UTC, andinomm approved these changes

2021-09-15 15:00 UTC, ioana-matei approved these changes

2021-09-15 16:00 UTC, IuliaMoldovan requested changes

2021-09-15 16:00 UTC, IuliaMoldovan commented on content/io/cloudslang/microsoft/azure/active_directory/user_management/create_user.sl
> +#! @result SUCCESS: Token generated successfully.
Here the description needs to be changed.

2021-09-16 09:51 UTC, IuliaMoldovan approved these changes

2021-09-16 11:48 UTC, merged