Created a operation for Delete instance
CloudSlang/cloud-slang-content pull request #1607
Opened 2022-08-11 05:06 UTC by manjoosh12

Created a operation for Delete instance

2022-08-22 15:19 UTC, umavanth21 requested changes
Please change the description like below:
zone: The zone in which the instance resides.

2022-08-24 04:29 UTC, manjoosh12 commented
> Please change the description like below: zone: The zone in which the instance resides.

updated the description @umavanth

2022-08-24 04:37 UTC, umavanth21 approved these changes

2022-08-24 04:38 UTC, KalyankarRajesh approved these changes

2022-08-24 04:38 UTC, merged