Gcp_attach_disk ,added mode and device_name  input properties
CloudSlang/cloud-slang-content pull request #1628
Opened 2022-11-16 07:21 UTC by Sailakshith6

2022-11-16 07:26 UTC, umavanth21 requested changes
Please check whether u followed best practices.

2022-11-16 16:52 UTC, KalyankarRajesh requested changes
Update the description for mode property (Default and Valid Values missing)

2022-11-17 11:22 UTC, KalyankarRajesh approved these changes

2022-11-18 05:12 UTC, patmante approved these changes

2022-11-18 07:27 UTC, umavanth21 approved these changes

2022-11-18 07:28 UTC, merged