Created operation to create or add tags to a resource in Azure and ad…
CloudSlang/cloud-slang-content pull request #1629
Opened 2022-11-16 16:00 UTC by ArthyVenk

…ded a python flow to convert the comma separated values to JSON format

2022-11-16 16:46 UTC, KalyankarRajesh requested changes
Update the namespace and property description.

2022-11-17 02:15 UTC, umavanth21 reviewed
- check line no 79 -is it pointing to test?
- auth token - please follow the same definition as used in other flows
- keys and values - can we say tag name and tag value , please revisit this description

2022-11-18 05:13 UTC, KalyankarRajesh approved these changes

2022-11-18 07:23 UTC, umavanth21 approved these changes

2022-11-18 07:30 UTC, merged