Added "List tiers" operation
CloudSlang/cloud-slang-content pull request #1681
Opened 2023-03-02 09:21 UTC by ArthyVenk

2023-03-02 09:39 UTC, umavanth21 reviewed
are we not using clientid and clientsecret for this operation?

2023-03-02 09:55 UTC, ArthyVenk commented
> 

No uma. We will get only the access token. We are not generating access token here in this operation

2023-03-02 10:38 UTC, umavanth21 commented
> > 
> 
> No uma. We will get only the access token. We are not generating access token here in this operation

ok got it Arthy

2023-03-02 10:38 UTC, umavanth21 approved these changes

2023-03-02 13:05 UTC, patmante requested changes

2023-03-02 13:05 UTC, patmante commented on content/io/cloudslang/google/databases/list_tiers.sl
> +#! @output instances_json: A JSON list containing the Instances information.
change the output name and description

2023-03-02 13:05 UTC, patmante commented on content/io/cloudslang/google/databases/list_tiers.sl
> +            - instances_json: '${return_result}'
here also update the output name

2023-03-03 04:49 UTC, ArthyVenk commented on content/io/cloudslang/google/databases/list_tiers.sl
> +            - instances_json: '${return_result}'
Updated

2023-03-03 05:57 UTC, patmante approved these changes

2023-03-03 09:22 UTC, merged