Created get_database_instance operation
CloudSlang/cloud-slang-content pull request #1692
Opened 2023-03-10 08:17 UTC by Sailakshith6

Created get_database_instance.sl and a python Operation get_database_instance_details.sl to extract details from json

2023-03-10 11:35 UTC, KalyankarRajesh approved these changes

2023-03-10 11:49 UTC, umavanth21 approved these changes

2023-03-10 11:52 UTC, patmante requested changes

2023-03-10 11:52 UTC, patmante commented on content/io/cloudslang/google/databases/instances/get_database_instance.sl
> +#! @description: This operation can be used to retrieve the DB Instance Details .
Update the description to **This operation is used to retrieve the DB instance details.**

2023-03-10 11:52 UTC, patmante commented on content/io/cloudslang/google/databases/instances/get_database_instance.sl
> +#! @input instance: Name of the DB Instance
* I think the input should be **instance_prefix** not instance.
use sentence case **"The name of the database instance"**  use Database instead of DB

2023-03-10 11:52 UTC, patmante commented on content/io/cloudslang/google/databases/instances/get_database_instance.sl
> +#! @output instance_state: The current serving state of the Cloud SQL instance.
Update to: **The current current state of the database instance.**

2023-03-10 11:52 UTC, patmante commented on content/io/cloudslang/google/databases/instances/get_database_instance.sl
> +#! @output instance_name: Name of the DB Instance
The name of the database instance.

2023-03-10 11:52 UTC, patmante commented on content/io/cloudslang/google/databases/instances/get_database_instance.sl
> +#!                           Valid values: - ZONAL: The instance serves data from only one zone.
Update the description here valid values are not needed this is output

2023-03-10 11:52 UTC, patmante commented on content/io/cloudslang/google/databases/instances/get_database_instance.sl
> +#! @output public_ip: The public ip of the instance.
it should be public_ip_address and also update the description.

2023-03-10 11:52 UTC, patmante commented on content/io/cloudslang/google/databases/instances/get_database_instance.sl
> +#! @result SUCCESS: The instance details were found and successfully retrieved.
Update the description.

2023-03-13 03:57 UTC, ArthyVenk approved these changes

2023-03-13 07:32 UTC, patmante requested changes

2023-03-13 07:32 UTC, patmante commented on content/io/cloudslang/google/databases/instances/get_database_instance.sl
> +#! @output region: The name of the zone in which the disks has to be created.
update the description

2023-03-13 07:32 UTC, patmante commented on content/io/cloudslang/google/databases/instances/get_database_instance.sl
> +#! @description: This operation is used to retrieve the Database instance details.
update it to **database** instead of **Database**

2023-03-13 07:32 UTC, patmante commented on content/io/cloudslang/google/databases/instances/get_database_instance.sl
> +#! @output instances_json: A JSON list containing the Instances information.
use sentence case

2023-03-13 07:32 UTC, patmante commented on content/io/cloudslang/google/databases/instances/get_database_instance.sl
> +#! @result SUCCESS: The Database instance details successfully retrieved.
use sentence case

2023-03-13 07:32 UTC, patmante commented on content/io/cloudslang/google/databases/instances/get_database_instance.sl
> +#! @input instance_name_prefix: The name of the database instance
can you check we need **instance id** or **instance name** as input?

2023-03-13 10:39 UTC, patmante approved these changes

2023-03-13 10:40 UTC, merged