Created Stop database Instance Operation and gcp stop database instance workflow and updated output property in get instance
CloudSlang/cloud-slang-content pull request #1702
Opened 2023-03-15 10:44 UTC by Sailakshith6

Created Stop database Instance Operation and gcp stop database instance workflow and updated output property in get instance

2023-03-15 11:12 UTC, patmante requested changes

2023-03-15 11:12 UTC, patmante commented on content/io/cloudslang/google/databases/gcp_stop_database_instance.sl
> +#! @input instance_name: Name of the database Instance
use sentence case

2023-03-15 11:12 UTC, patmante commented on content/io/cloudslang/google/databases/instances/get_database_instance.sl
> +#! @output instance_json: A JSON list containing the Instances information.
update it to database_instance_json

2023-03-15 11:24 UTC, umavanth21 requested changes
Please try with v1 version instead of v1beta4, because beta may be not stable version.
https://cloud.google.com/sql/docs/mysql/start-stop-restart-instance#rest-v1_1

2023-03-16 04:32 UTC, umavanth21 approved these changes

2023-03-16 09:17 UTC, patmante approved these changes

2023-03-16 09:42 UTC, merged