Created operation for Azure resize vm
CloudSlang/cloud-slang-content pull request #1733
Opened 2023-06-08 15:52 UTC by Sailakshith6

2023-06-15 11:33 UTC, patmante requested changes

2023-06-15 11:33 UTC, patmante commented on content/io/cloudslang/microsoft/azure/azure_update_vm_size.sl
> +#! @description: This workflow is used to update or resize the virtual machine.
update the description

2023-06-15 11:33 UTC, patmante commented on content/io/cloudslang/microsoft/azure/azure_update_vm_size.sl
> +#! @input tenant_id: The tenantId value used to control who can sign into the application.
it should be tenant id

2023-06-15 11:33 UTC, patmante commented on content/io/cloudslang/microsoft/azure/azure_update_vm_size.sl
> +#! @output power_state: Power state of the Virtual Machine
Use sentence case

2023-06-16 10:15 UTC, KalyankarRajesh approved these changes

2023-06-16 10:22 UTC, patmante approved these changes

2023-06-16 10:56 UTC, merged