Ansible - added users flows
CloudSlang/cloud-slang-content pull request #1872
Opened 2024-10-21 14:42 UTC by BoicuAlexandra

added:
- create_user
- delete_user 
- get_user_id
- list_users

2024-10-21 16:07 UTC, patmante requested changes

2024-10-21 16:07 UTC, patmante commented on content/io/cloudslang/redhat/ansible/automation_platform/users/create_user.sl
> +    - create_new_user:
Assign "worker_group" for each step to all flows
![image](https://github.com/user-attachments/assets/59d8a06e-ef85-4eee-b517-ca4d168a0b59)

2024-10-21 16:10 UTC, patmante requested changes

2024-10-21 16:10 UTC, patmante commented on content/io/cloudslang/redhat/ansible/automation_platform/users/create_user.sl
> +#! @input ansible_automation_platform_url: Ansible Tower API URL to connect to (example: https://192.168.10.10/api/v2)
use "the Ansible Automation Platform"  instead of Ansible Tower

2024-10-22 11:06 UTC, BoicuAlexandra commented on content/io/cloudslang/redhat/ansible/automation_platform/users/create_user.sl
> +#! @input ansible_automation_platform_url: Ansible Tower API URL to connect to (example: https://192.168.10.10/api/v2)
Done

2024-10-22 11:07 UTC, BoicuAlexandra commented on content/io/cloudslang/redhat/ansible/automation_platform/users/create_user.sl
> +    - create_new_user:
done

2024-10-23 05:17 UTC, patmante approved these changes

2024-10-23 05:17 UTC, Sailakshith6 approved these changes

2024-10-23 05:18 UTC, merged